kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster-dev
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraMounts:
      - hostPath: ./dags
        containerPath: /data/spark-apps/dags
      - hostPath: ./jobs
        containerPath: /data/spark-apps/jobs
      - hostPath: ./data
        containerPath: /data/spark-apps/data
    extraPortMappings:
      - containerPort: 8081
        hostPort: 8081
        protocol: TCP
      - containerPort: 8444
        hostPort: 8444
        protocol: TCP

  - role: worker
    extraMounts:                         
      - hostPath: ./dags
        containerPath: /data/spark-apps/dags
      - hostPath: ./jobs
        containerPath: /data/spark-apps/jobs
      - hostPath: ./data
        containerPath: /data/spark-apps/data
    extraPortMappings:
      - containerPort: 31001
        hostPort: 31001
        protocol: TCP

  - role: worker
    extraMounts:                        
      - hostPath: ./dags
        containerPath: /data/spark-apps/dags
      - hostPath: ./jobs
        containerPath: /data/spark-apps/jobs
      - hostPath: ./data
        containerPath: /data/spark-apps/data
    extraPortMappings:
      - containerPort: 31002
        hostPort: 31002
        protocol: TCP

  - role: worker
    extraMounts:                         
      - hostPath: ./dags
        containerPath: /data/spark-apps/dags
      - hostPath: ./jobs
        containerPath: /data/spark-apps/jobs
      - hostPath: ./data
        containerPath: /data/spark-apps/data
    extraPortMappings:
      - containerPort: 31000
        hostPort: 31000
        protocol: TCP
      - containerPort: 30003
        hostPort: 30003
        protocol: TCP
      - containerPort: 30004
        hostPort: 30004
        protocol: TCP
      - containerPort: 30005
        hostPort: 30005
        protocol: TCP
      - containerPort: 30006
        hostPort: 30006
        protocol: TCP
      - containerPort: 30007
        hostPort: 30007
        protocol: TCP
      - containerPort: 30008
        hostPort: 30008
        protocol: TCP
      - containerPort: 30009
        hostPort: 30009
        protocol: TCP
      - containerPort: 30010
        hostPort: 30010
        protocol: TCP